### ISSUE TITLE
error: addRange(): The given range isn't in document.

### ISSUE THREAD

**Issue by VeoScript** [mantinedev/mantine#1386]
### What package has an issue

@mantine/rte

### Describe the bug

I found an error while I uploading some photo in RichTextEditor.

Error: **quill.js?99f4:3195 addRange(): The given range isn't in document.**

![image](https://user-images.githubusercontent.com/26340308/166686595-3ed15599-d4a0-4b2b-8e4b-406a05e04e9b.png)

![image](https://user-images.githubusercontent.com/26340308/166686803-05214318-c266-43bf-9b5d-834161f45b3b.png)

### In which browser did the problem occur

Chrome

### Possible fix

I think the error is from the latest version of Quill.

**Comment by wes337** [comment]
This is a duplicate of #1288

**Comment by rtivital** [comment]
The PR was merged, will be fixed with next patch, thanks @wes337!

**Comment by Hartaithan** [comment]
> The PR was merged, will be fixed with next patch, thanks @wes337!

I have updated mantine to version 4.2.5, but I am still seeing this problem.
RichTextEditor file - [link](https://github.com/Hartaithan/next-posts/blob/main/components/Editor.tsx)
Code - [link](https://github.com/Hartaithan/next-posts)
Demo - [link](https://next-posts-hartaithan.vercel.app/) (Authorization is required to access the editor page)

**Comment by Hartaithan** [comment]
@wes337 Any updates?

**Comment by wes337** [comment]
I will take another look at this. It seems to be a bug from quilljs and there might be a workaround.

Would you be able to provide a code sandbox where this issue can be reproduced?

**Comment by rtivital** [comment]
Fixed in 4.2.7

**Comment by Hartaithan** [comment]
@rtivital @wes337 
Updated to version 4.2.7. Still seeing this problem. But now file input is not triggered multiple times. And the image is displayed blurred, even after successfully loading the image.
[Preview](https://s191vla.storage.yandex.net/rdisk/739c263b728e41e47700ebb4643d44c4f8794aec4cb11c331d0c8c22bdd87262/629b454d/HHUG9ervwW7QUMLk9FbJG8-HAbTG0R-GZbO7RaiKlwNU1hxdkTeCw2lFstQtBaRM-atds3LMZyNi1vEQtvsUyg==?uid=222881247&filename=mantine.gif&disposition=inline&hash=&limit=0&content_type=image%2Fgif&owner_uid=222881247&fsize=1747093&hid=15800c014af106fa805db08f516ea952&media_type=image&tknv=v2&etag=179a0b6f03306f789f60761393e7c749&rtoken=Fj3u8gIiGyVl&force_default=yes&ycrid=na-3185b2e2d52b98fa04ba97405a85c08a-downloader6f&ts=5e09dbe322d40&s=114429edfc4cb5e5a7f8b9bd229d6137fecec775c627338d539ef894edfc8fb0&pb=U2FsdGVkX183c9zTm8-YHQha2AqxdKviFkIus232ni2RCJiFkzxM68FVbXWrxzE3qppgnARGm2lkXs0_rvWk4XXO2WtT_pHL9WwAaXciHGE)

**Comment by wes337** [comment]
I think there's been some confusion about this issue and the related issues, and I would really like to clear this up.

There are 2 different issues here:
1. `addRange(): The given range isn't in document.`. - This is a warning coming from quill. It's not causing anything to break, and is only shown in the console when React strict mode is enabled. I do not know if this is actually related to or the cause of the issue you are facing.

2. `TypeError: Cannot read properties of null (reading 'index')` - This is an error. It was caused by a bug in Mantine's `ImageUploader` file. It's been fixed for images.
[
If this is the code you are showing in your preview](https://github.com/Hartaithan/next-posts/blob/main/components/Editor.tsx#L24), then you should probably check if `res.image_url` is correct. It is probably `res.data.image_url`.

**Comment by Hartaithan** [comment]
@wes337 
No, that's not the problem.
[Here's](https://i.ibb.co/LvWkvQb/imageupload.png) console.logged output from res object, there's no data object

**Comment by wes337** [comment]
Check the URL, is the image really uploading correctly? For example that link from the console logged output (https://res.cloudinary.com/d19b8yqr4/image/upload/v1654335366/t9wbgxa9arvp39gcmfnn.jpg) is showing:

![image](https://user-images.githubusercontent.com/9464690/172000438-a29bd28e-fbd6-4a50-9f71-0095ad3f2ab0.png)

I don't think your problem is coming from Mantine's code

**Comment by wes337** [comment]
@Hartaithan 
Sorry, but I can't reproduce this from my end. I'm still not even sure if your problem is related to this original issue.
