### ISSUE TITLE
RichTextEditor image upload (Cannot read properties of null (reading 'index'))

### ISSUE THREAD

**Issue by timahuna** [mantinedev/mantine#1508]
### What package has an issue

@mantine/rte

### Describe the bug

1. Wrap react app in a Strict Mode component. 
2. Add a RichTextEditor component. 
3. Add an image via the embed image icon in the toolbar:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/104216931/170070300-2a62d14a-3f1c-45cc-8d9c-8bc539cad3a7.png">
4. You should see the error `Cannot read properties of null (reading 'index')`

Drag/drop works, pasting works, just the toolbar is causing this error (when wrapped in `<StrictMode>`). 

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/bold-field-ilkjez?file=/src/App.js

### Do you know how to fix the issue

No

### Possible fix

Looks like this.range is reset in the [ImageUploader](https://github.com/mantinedev/mantine/blob/master/src/mantine-rte/src/modules/image-uploader/ImageUploader.ts#L139) in strict mode.  

I could be wrong (and I haven't tested this) but I think we might want to set the range [here](https://github.com/mantinedev/mantine/blob/ea0b78ca7bca36c821f34ff34f47d161f82a1288/src/mantine-rte/src/modules/image-uploader/ImageUploader.ts#L139) via `this.range = this.quill.getSelection();`.

**Comment by wes337** [comment]
Duplicate of or closely related to #1386

**Comment by rtivital** [comment]
Fixed in 4.2.7

**Comment by mvskvortsov** [comment]
I'm still have this error on almost all of toolbar button: lists, image... And "addRange(): The given range isn't in document." on other toolbar buttons.

**Comment by wes337** [comment]
> I'm still have this error on almost all of toolbar button: lists, image... And "addRange(): The given range isn't in document." on other toolbar buttons.

I'm seeing it on lists too. But it is fixed with images, just make sure you're using at least version 4.2.7

**Comment by rtivital** [comment]
The issue happens only in with react strict mode, disable strict mode to fix it. The issue cannot currently be resolved on library side.

**Comment by lucasvilaca27** [comment]
### ###

**Comment by lucasvilaca27** [comment]
****
