### ISSUE TITLE
Encountered two children with the same key warning - Select with creatable prop

### ISSUE THREAD

**Issue by osolliec** [mantinedev/mantine#1662]
### What package has an issue

@mantine/core

### Describe the bug

Warning of duplicate keys when you hover on options if you have the creatable prop enabled.
![image](https://user-images.githubusercontent.com/22033728/174816527-84c6cdf6-bdee-4c98-8597-ea8e874a33fb.png)

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/cocky-currying-hlkgei?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment]
`shouldCreate` function determines whether creatable option should be displayed in the list, in the provided sandbox it always returns true, and thus creatable option is always rendered.

**Comment by rtivital** [comment]
Fixed in 5.1.5

**Comment by pencilcheck** [comment]
I'm on 6.0.5 for some reason on MultiSelect I'm still getting this error with createable props.
