### ISSUE TITLE
AutoComplete on app Shell act strange

### ISSUE THREAD

**Issue by IAFahim** [mantinedev/mantine#1858]
### What package has an issue

@mantine/core

### Describe the bug

As taken from the app example of Auto Complete
it acts glitched in appshell and it also creates scroll wheel on page as it overflows.

https://user-images.githubusercontent.com/63500913/180828069-d701a56a-8ebd-4e8e-b1f9-ab6cef62d86b.mp4

### In which browser did the problem occur

firefox

### If possible, please include a link to a codesandbox with the reproduced problem

https://github.com/IAFahim/uni/blob/master/src/Components/Clubs/Clubs.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

### Possible fix

I don't know yet, very very noob

**Comment by rtivital** [comment]
Should be fixed in 5.0 with Floating UI migration

**Comment by gonzoramos** [comment]
Has the fix been pushed? As of 5.0.2 the problem still persists :(

**Comment by IAFahim** [comment]
Yes, its still a problem. Still waiting for fix hehe
@gonzoramos
