### ISSUE TITLE
Tooltip position not working correctly with RTL

### ISSUE THREAD

**Issue by ShahriarKh** [mantinedev/mantine#2104]
### What package has an issue

@mantine/core

### Describe the bug

The position of tooltip is incorrect in RTL mode. For example, choosing "Right" in RTL renders the tooltip on the left side.

# LTR (correct)
![image](https://user-images.githubusercontent.com/31452340/184502846-423b5ae8-8d27-48b7-a5ee-7ddc6f7e6545.png)

# RTL (incorrect)
![image](https://user-images.githubusercontent.com/31452340/184502855-3e199934-9ca8-4616-b56c-720a991d5d9b.png)

### What version of @mantine/hooks page do you have in package.json?

5.1.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

I need to take a look at the source code.

**Comment by ShahriarKh** [comment]
Just took a quick look at source code. I think this line is causing the problem (since it's using `theme.dir`):
https://github.com/mantinedev/mantine/blob/73c0e3a6068554cb5e214c60ae975db9b1979879/src/mantine-core/src/Tooltip/Tooltip.tsx#L110-L111

**Comment by ShahriarKh** [comment]
I'm taking a look at other components and will update the list of affected components below:
- Tooltip
- Menu

**Comment by rtivital** [comment]
Flipping position is the correct logic – if you are building website that uses both rtl and ltr, you would want those positions flipped. The prop on theme to configure this behavior will be nice though. The arrow position is not correct, it should be fixed.

**Comment by ShahriarKh** [comment]
I see... so, how can I contribute to add that prop?

**Comment by rtivital** [comment]
Yes, sure, feel free to send a PR, if you can also fix the arrow position for rtl that would be great

**Comment by ShahriarKh** [comment]
Okay, I will take a look at the code and see what I can do!

**Comment by rtivital** [comment]
Fixed in 5.1.7

**Comment by ShaMan123** [comment]
This is not fixed


![image](https://github.com/mantinedev/mantine/assets/34343793/0ffbbb8d-9edd-4cc7-b088-eecd523a6308)
