### ISSUE TITLE
Wrong alignment behavior with Tooltip/Popover components

### ISSUE THREAD

**Issue by 7iomka** [mantinedev/mantine#2500]
### What package has an issue

@mantine/core

### Describe the bug

I like that you choose to go with Floating UI as a base for all tooltips, dropdowns, etc...
I love Floating UI, but with mantine I don't have the same behavior.

Image you have a tooltip text with approx. maximum width 450px.
Also you support responsiveness for at least 320px.

We have different behavior than expected (as in Floating UI) in this cases:
- when width of tooltip is not enough to to fill free space between target and direction side
- when viewport is less then width of tooltip

Expected behavior
Default (when free space is enough)
<img width="698" alt="Снимок экрана 2022-09-20 в 04 23 30" src="https://user-images.githubusercontent.com/18473137/191153187-9439f1e7-6a48-4baf-b134-c607ce79f3be.png">

When free space is not enough:
<img width="508" alt="Снимок экрана 2022-09-20 в 04 23 18" src="https://user-images.githubusercontent.com/18473137/191153037-b348a664-afcd-4eea-94bd-ee11c99834c7.png">

 

Actual behavior
- for both cases we have broken layout - content of tooltip is outside of viewport, or for multiline target it has broken alignment (especially when arrow is enabled)

<img width="410" alt="image" src="https://user-images.githubusercontent.com/18473137/191153633-e9aeb13c-515e-462a-95dd-f91267c59fa9.png">
<img width="653" alt="image" src="https://user-images.githubusercontent.com/18473137/191153681-00dddd7d-a15d-4c57-82e8-2139e96efceb.png">

[LINK FOR DEMO](https://codesandbox.io/p/github/7iomka/effector-react-form-flow/draft/wandering-morning?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A38%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A38%2C%22startLineNumber%22%3A9%7D%5D)

### What version of @mantine/hooks page do you have in package.json?

latest

### Possible fix

Refactor logic to prevent usage of direct width value (maxWidth is preferable), also I think you need to research edge cases

**Comment by 7iomka** [comment]
Similar case
https://user-images.githubusercontent.com/18473137/191240527-777147cf-8daa-40eb-828c-ec3120808ebc.mov

**Comment by rtivital** [comment]
Fixed in 5.5.0

**Comment by 7iomka** [comment]
@rtivital For me issue still present :(

1) Open the [DEMO](https://codesandbox.io/p/github/7iomka/effector-react-form-flow/draft/angry-kepler?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A32%2C%22endLineNumber%22%3A25%2C%22startColumn%22%3A32%2C%22startLineNumber%22%3A25%7D%5D)
2) Hover once to show tooltip first time. Then, resize ui window to the minimum allowed size, then try again to hover to tooltip trigger (`(i)`) multiple times, you will see weird behavior like one that I have and demonstrated you in video from above. Note, that I have this issue without resizes and etc., but maybe it's a common case, and if a fix for this exists, maybe it will help me.

**Comment by rtivital** [comment]
No idea about that, maybe some issue with floating ui. Anyway, the issue was originally about arrow position and inline tooltip, the shift of tooltip is probably unrelated.

**Comment by atomiks** [comment]
Hey @rtivital I think the issue is this:

https://github.com/mantinedev/mantine/blob/aa3b261914a873ede6ade244cda5df8812aec71c/src/mantine-core/src/Tooltip/Tooltip.tsx#L153-L154

The `?? ''` should be `?? 0`. By laying out the element at the top-left of the screen initially, it will have its "final" dimensions ready. Currently, it gets resized by the layout when at the right of the screen, which causes it to have smaller initial dimensions than it should.

More info:

<img width="724" alt="Screen Shot 2022-10-16 at 6 08 12 am" src="https://user-images.githubusercontent.com/22450188/196003870-b1f8d9ce-fe80-42f3-9527-de1aa087d35e.png">

**Comment by rtivital** [comment]
Thanks, @atomiks, I'll change that to zero. I remember taking this exact logic from one of the floating ui examples about 4 months, it must have been changed since then.

**Comment by rtivital** [comment]
I've changed empty string to `0` in `5.5.6`, it will be out soon

**Comment by atomiks** [comment]
I think it should also be down for Popover:

https://github.com/mantinedev/mantine/blob/4fa634ebddf15a8515a9018e37b1e86d2e00883a/src/mantine-core/src/Popover/PopoverDropdown/PopoverDropdown.tsx#L71-L72

Another thing I discovered: if you resize the window to be narrow after it gets positioned for the first time, it can have the wrong position for subsequent renders. (Assuming the `useFloating()` hook does not get unmounted between renders).

There are two fixes for that:

- Set [`width: max-content`](https://developer.mozilla.org/en-US/docs/Web/CSS/max-content) on the floating element. This ensures parent containers do not affect its layout or dimensions no matter where it is located on the document.
- Use `transform: translate()` for the coordinates, and keep `top/left` to `0` at all times. The layout will not be affected in this case either, and its dimensions will be full size even when it pushes up against the edge of the document.

**Comment by rtivital** [comment]
I've added the same changes as in Tooltip to Popover and set width: max-content
