### ISSUE TITLE
Controlled NumberInput does not display controlled value

### ISSUE THREAD

**Issue by lscheibel** [mantinedev/mantine#2782]
### What package has an issue

@mantine/core

### Describe the bug

The NumberInput maintains its own input state and does not reflect the value that it is given. The Codesandbox illustrates this nicely.

### What version of @mantine/hooks page do you have in package.json?

5.6.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/stoic-golick-ill59o

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

The most obvious bug seems to be the ` && !focused` condition in line 249 in NumberInput.tsx

**Comment by tadeas-vintrlik** [comment]
I looked into it a little bit and I have come to the conclusion that there is no good way around this.

The type of value of all inputs is string. The `NumberInput` claims that it is `number | undefined`. Since this cannot be the case it maintains its' own internal value.

The only solutions that comes to mind is if the actual type of `value` was string with the guarantee that it is in fact a valid `number` type once parsed. This would be farther complicated by the fact that `NumberInput` supports a `formatter` and `parser` callbacks as props which allow adding additional characters to the input which need not be a number such as a '$'.

**Comment by NWPoul** [comment]
> The type of value of all inputs is string. The `NumberInput` claims that it is `number | undefined`. Since this cannot be the case it maintains its' own internal value.
> 
This makes my TS unhappy even in exact example provided by Mantine docs
_"Argument of type 'number | undefined' is not assignable to parameter of type 'SetStateAction<number>"_

Would it be more straightforward if NumberInput utilize
native HTMLInputElement.valueAsNumber property?

**Comment by rtivital** [comment]
Fixed in 6.0

**Comment by furkanonb** [comment]
Seems this issue isn't fixed. I'm using `"@mantine/core": "^7.14.3", `  and I get the same problem
