### ISSUE TITLE
Mantine select example has a z-index issue on the examples page

### ISSUE THREAD

**Issue by epicmau5time** [mantinedev/mantine#2952]
### What package has an issue

@mantine/core

### Describe the bug

An example of the issue can be seen below

![image](https://user-images.githubusercontent.com/13358902/201546426-ce30bda3-ca9c-49fd-9bfd-e8bc9128741a.png)

### What version of @mantine/hooks page do you have in package.json?

5.7.2

**Comment by rtivital** [comment]
Fixed in 5.8.2

**Comment by kuntik17** [comment]
I still have this issue.. 
![Screenshot 2022-12-14 at 22 18 17](https://user-images.githubusercontent.com/43724968/207694259-fba720fc-b384-410c-8da6-e8ee1bf19eaa.png)

**Comment by rtivital** [comment]
Set `<Select withinPortal />`

**Comment by kuntik17** [comment]
@rtivital saved my day, thanks!!!

**Comment by aheissenberger** [comment]
please add a short section with the property "withinPortal" to the documentation - thanks
