### ISSUE TITLE
onBlur is triggered whenever we click on Rich Text Editor Controls

### ISSUE THREAD

**Issue by Avas77** [mantinedev/mantine#3209]
### What package has an issue

@mantine/tiptap

### Describe the bug

I am trying to show the Rich Text Editor controls only when the text editor is focused. It works but whenever I click on the text editor control buttons like Link, Bold etc, the onBlur event is also triggered and the text editor control gets hidden

### What version of @mantine/hooks page do you have in package.json?

5.9.3

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/fervent-minsky-4wv5yh?file=/src/Editor.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by patrickserrano** [comment]
Just wanted to see if there was any update on this? I wanted to save the contents of the editor onBlur but it's a little clunky if formatting triggers a save.

**Comment by rtivital** [comment]
The issue is resolved in [7.0.1](https://github.com/mantinedev/mantine/releases/tag/7.0.1)

**Comment by weehung-livex** [comment]
I still face this issue as i want to have the editor to save on blur, when i use the mantine inbuilt link component which creates a popover, it will trigger on blur with the first click, then open the popover successfully on the second click.

i am on ^7.17.7 for the mantine tiptap versions

**Comment by rtivital** [comment]
I cannot reproduce this issue. The focus is moved correctly, and you need to press the button only once.

https://github.com/user-attachments/assets/6521da1f-1bea-4338-a488-7b18d947c97d

**Comment by weehung-livex** [comment]
Yep, sorry for late response. I have figured that its due to how i mount the component. 

if i do this, it works as expected
```
const getLinkControls = () => {
    return (
      <MantineRichTextEditor.ControlsGroup>
        <MantineRichTextEditor.Link />
        <MantineRichTextEditor.Unlink />
      </MantineRichTextEditor.ControlsGroup>
    );
  };
///// use it as a function
{getLinkControls()}

```


if i do this, the issue will be reproduced:
```
const LinkControls = () => {
    return (
      <MantineRichTextEditor.ControlsGroup>
        <MantineRichTextEditor.Link />
        <MantineRichTextEditor.Unlink />
      </MantineRichTextEditor.ControlsGroup>
    );
  };
///// use it as a component
<LinkControls />

```
