### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by npearson72** [mantinedev/mantine#4268]
### What package has an issue

@mantine/core

### Describe the bug

I discovered the following error `ResizeObserver loop limit exceeded` when using `Popover`, but it seems to be related to `@floating-ui`

See: https://github.com/floating-ui/floating-ui/issues/1740

### What version of @mantine/hooks page do you have in package.json?

6.0.1

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

The fix is described in https://github.com/floating-ui/floating-ui/issues/1740

Here is an example of how someone else fixed it: https://github.com/TalismanSociety/talisman-web/pull/602/files

I believe all that would be needed to resolve it would be to change this code:

https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Popover/use-popover.ts#L75-L91

Like so:

```ts
const floating = useFloating({
    placement: options.position,
    middleware: [
      ...getPopoverMiddlewares(options),
      ...(options.width === 'target'
        ? [
            size({
              apply({ rects }) {
                requestAnimationFrame(() => {
                  Object.assign(floating.refs.floating.current?.style ?? {}, {
                    width: `${rects.reference.width}px`,
                  });
                });
              },
            }),
          ]
        : []),
    ],
  });

```

However, something similar might be needed for the middlewares?

I'm not sure why this isn't resolved upstream at `@floating-ui` but the feedback in the referenced issue seemed to defer to user land.

**Comment by npearson72** [comment]
@atomiks thanks for jumping in here. Are you suggesting this issue be reposted to floating ui for support?

**Comment by atomiks** [comment]
I've re-opened the existing issue that was closed

**Comment by cbelsole** [comment]
FYI: This happened to us. We tracked it down to the Select component.

**Comment by npearson72** [comment]
Re-opening this ticket based on these comments: https://github.com/floating-ui/floating-ui/pull/2335#issuecomment-1556269031

**Comment by rtivital** [comment]
I do not understand what changes we need to make to the Popover component to fix the issue. You (or anyone else) are welcome to send a PR with a fix.

**Comment by MA-MacDonald** [comment]
I am running into this issue as well.
It appears to happen when a Select/MultiSelect is allowed to resize within a flex container. 
If i move the Select outside of a flex container or hard code a width for the Select it does not give the error.

**Comment by cau777** [comment]
Hi, I'm also running into this issue.
It's happening in 2 distinct places:
1. In a `<Modal/>` that contains `<Select/>`, `<DatePicker/>` and `<TextInput/>` components
2. In a `<Popover/>` that contains `<TextInput/>` components. Those components have a fixed width specified in `styles`.

I see this error happening a lot but only to a couple of users.
I tried a bunch of things, but couldn't reproduce the issue in my machine.

I'd really appreciate some help

**Comment by EduardoCastanho** [comment]
Hi,

In my case, `Modal` with a `Select` inside,
if I use attribute `withinPortal={true}` in `Select` the problem goes away and all works fine.

I think is related with the Select dropdown size conflicting with Modal size.

**Comment by cyantree** [comment]
Can you create an example that shows this behaviour?
I've tried recreating it with a `Select` within a `Modal` but failed so far.

**Comment by atomiks** [comment]
A cause of this error should be fixed now if you re-install Mantine so it picks up `@floating-ui/dom@1.4.3` (a transitive dependency). Clear the cache and verify if that version successfully installed in your lockfile or node_modules folder.

**Comment by knightjdr** [comment]
> A cause of this error should be fixed now if you re-install Mantine so it picks up `@floating-ui/dom@1.4.3` (a transitive dependency). Clear the cache and verify if that version successfully installed in your lockfile or node_modules folder.

This did not fix it for me. I reinstalled and cleared the cache. I can see the specified version in my lock file:
```
  "name": "@floating-ui/dom",
  "version": "1.4.3",
```

I'm using the Autocomplete component in a Modal.

The error is sporadic though. In my component tests I don't get the error when running one test at a time, but get it occasionally when running them as a group. So for now I'm just ignoring the error in my tests.

**Comment by GrahamOrmond** [comment]
> Hi,
> 
> In my case, `Modal` with a `Select` inside, if I use attribute `withinPortal={true}` in `Select` the problem goes away and all works fine.
> 
> I think is related with the Select dropdown size conflicting with Modal size.

setting the overflow to 'visible' for the modal content solved it for me. 

`<Modal styles={{
        content: {
          overflow: 'visible !important'
        }
      }} />`

**Comment by fated-x** [comment]
@GrahamOrmond - your solution works, but you lose your modal's scrollbar. We need something better.

**Comment by rtivital** [comment]
I've not been able to reproduce the issue after floating-ui package has been updated to the latest version (0.26.9).

**Comment by micro9000** [comment]
I'm getting similar error "ResizeObserver loop completed with undelivered notifications" on Group component
I can ignore the error by using useResizeObserver() hook and assigned a ref value to the Group component but I don't like doing that in every page that I have Group.

I'm using mantine version 5.2.3

Do I need to upgrade to get rid of that error?

**Comment by leadq** [comment]
Is there any solution without updating mantine ? Like just updating the floating ui thing only somehow ? Because we are using the old version of mantine in our huge project and installing  the latest version could be painful

**Comment by rtivital** [comment]
You can try updating dependencies in your lock file to specific version of floating ui. You can also patch package. Note that older versions of Mantine may not work with newer version of floating ui because of breaking changes in floating ui.

**Comment by matttk** [comment]
Same as @MA-MacDonald - I am using `MultiSelect` and when I give it a fixed width, the problem goes away.

I'm using Mantine version 7.12.2.

**Comment by matttk** [comment]
> I've not been able to reproduce the issue after floating-ui package has been updated to the latest version (0.26.9).

My `package-lock.json` says version 0.26.23 and I still have the issue with `MultiSelect`.

**Comment by matttk** [comment]
For me it also happens always with `DatePicker` when you choose the last date in the box.

![image](https://github.com/user-attachments/assets/367f49c1-916c-42e1-b4f0-5807e351d699)

So when I click now with my mouse, I'll get the error, 100% of the time. However, I am aware that it doesn't happen in [the example from the docs](https://mantine.dev/dates/date-picker-input/#dates-range) (not sure what's different).

**Comment by Hachondeoro** [comment]
> Same as [@MA-MacDonald](https://github.com/MA-MacDonald) - I am using `MultiSelect` and when I give it a fixed width, the problem goes away.
> 
> I'm using Mantine version 7.12.2.

This works for me too, I implemented it like this:
```javascript
<div style={{ width: "300px" }}> {/* Set a fixed width for the container */}
          <Select
            .......
          />
        </div>
```

**Comment by an-tran511** [comment]
i am having the same problem with multi select

**Comment by rtivital** [comment]
Comments for this issue are locked, if you want to report an issue, create a sandbox with a reproduction and submit a new issue on GitHub.
