### ISSUE TITLE
Sometimes `Transition` renders child instanly

### ISSUE THREAD

**Issue by dokugo** [mantinedev/mantine#5193]
### What package has an issue

@mantine/core

### Describe the bug

Sometimes `Transition` renders child instanly without actually transitioning, this happens when `Transition` status is currently `exited` and then its `mounted` prop value changes from `false` to `true`.

Here is the code to reproduce the problem:
https://codesandbox.io/p/devbox/mantine-transition-test-next-4dfvdc

Here is the screen recording. I toggle `isVisible` boolean value by clicking the first button. `isVisible` is used as the value of `mounted` `Transition` prop. After a few toggles the hidden button appears instantly.

https://github.com/mantinedev/mantine/assets/7773972/6d6ecade-7c68-4bc9-af80-5dee2ef9f059

Simulation of fast toggling:

https://github.com/mantinedev/mantine/assets/7773972/f02d2584-e769-486c-b322-dc8c1db66700

I'm not sure why exactly this happens. I tried experimenting with `flushSync` inside the `handleStateChange` function here, but without success.
https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/components/Transition/use-transition.ts#L41

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.7

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/p/devbox/mantine-transition-test-next-4dfvdc

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by ID-JA** [comment]
Hi @rtivital, I've tackled the issue and implemented a solution. Would it be possible for me to create a PR for your review?

**Comment by ghana7989** [comment]
Sandbox link is not working

**Comment by dokugo** [comment]
@ghana7989 thanks, I fixed the link.

**Comment by cyantree** [comment]
I think that's the same issue as #3126.

**Comment by cyantree** [comment]
Please have a look at [this comment](https://github.com/mantinedev/mantine/issues/3126#issuecomment-1962409265) where I've provided an example using a patched version of the library.

Could you please check whether this resolves the issue for you?

**Comment by rtivital** [comment]
Fixed in [7.6.1](https://github.com/mantinedev/mantine/releases/tag/7.6.1)

**Comment by fauxparse** [comment]
> Fixed in [7.6.1](https://github.com/mantinedev/mantine/releases/tag/7.6.1)

It's still happening in the stories on the Mantine website, FYI :)

**Comment by devnaumov** [comment]
@rtivital Still happening for the modals manager example on the Mantine website. Modal opens instantly after several attempts.
