### ISSUE TITLE
SSR Styling issue

### ISSUE THREAD

**Issue by juan-manuel-alberro** [mantinedev/mantine#53]
Hi, I'm using Next.js (Blitz.js) and there's an issue with the example provided in [here](https://mantine.dev/guides/ssr/).
When I refresh the page in a particular route (/login for example) all the styles are removed (SSR rendering)

![no-styles](https://user-images.githubusercontent.com/7114488/117535951-52bc0e00-aff0-11eb-8e40-0be8c5d0d813.png)

And it seems to be related to the `useEffect` from the `_app.js` mentioned in the guide

```js
  useEffect(() => {
    const jssStyles = document.getElementById("mantine-ssr-styles")
    if (jssStyles) {
      jssStyles.parentElement.removeChild(jssStyles)
    }
  }, [])
```

If I remove that the styles are in place again when I refresh the route `/login` but the theme `light/dark` isn't working, the elements don't switch the theme properly.

In the main route `localhost:3000` the issue is not reproducible, only in internal routes.

I'm using the latest `mantine` version with `react-jss`.

**Comment by rtivital** [comment]
Hi Juan, I've noticed something similar before with next, but was not able to reproduce that after restarting the server.
Can you share the source code which produces this behavior? If not, can you check if javascript part (like events handlers) of application is still works? My best guess is that js bundle is not loaded.

**Comment by juan-manuel-alberro** [comment]
Hi @rtivital, here are the files `_app.jsx` and `_document.tsx`

https://gist.github.com/juan-manuel-alberro/193c3b04266c0fefdbf4167bab3de7db

Let me know if you need any other file,

**Comment by rtivital** [comment]
The one thing which is definitely not right  – [createUseStyles inside component](https://gist.github.com/juan-manuel-alberro/193c3b04266c0fefdbf4167bab3de7db#file-_app-jsx-L34-L44), see https://mantine.dev/guides/dark-theme/#global-styles for correct example. I do not think that this is the case for broken scripts loading, to debug that I need to launch this locally and see what `<BlitzScript />` component renders.

**Comment by rtivital** [comment]
Does production build have correct styles on this page?

**Comment by juan-manuel-alberro** [comment]
Well, if I remove the 

```jsx
  useEffect(() => {
    const jssStyles = document.getElementById("mantine-ssr-styles")
    if (jssStyles) {
      jssStyles.parentElement.removeChild(jssStyles)
    }
  }, [])
```
Now it renders properly from the SSR as well, and the theme switch is also working. 
What are the implicates of removing that? Probably is not the best option 😄

**Comment by rtivital** [comment]
Yep, server side styles should be removed to avoid performance issues.
Maybe something is wrong with hydration.
Can you try out your login page in our next example project to see if we can replicate the issue there?
- `git clone https://github.com/mantinedev/mantine-next-http-status-code`
- `yarn`
- Add login.tsx page with your components
- Check if it works in development
- `npm run build && npm start`
- Check if production build works

**Comment by rtivital** [comment]
I've managed to replicate SSR issue with mantine docs. If you refresh page with component which uses Portal (e.g. Modal) some styles will be corrupted – https://mantine.dev/core/drawer/
These two things must be connected

**Comment by rtivital** [comment]
@juan-manuel-alberro I've released a fix to Portal component, can you please update all your @mantine/ scoped packages to version 1.0.5 and check if this resolves the issue?

**Comment by rtivital** [comment]
I've run some tests with Next.js and [fixed some issues](https://github.com/mantinedev/mantine/releases/tag/1.0.6), not sure that this will fix this issue but let's try anyway, I'm running out of ideas.

In package.json set fixed version for all @mantine/ packages:
```json
  "dependencies": {
    "@mantine/core": "1.0.6",
    "@mantine/hooks": "1.0.6",
    "@mantine/notifications": "1.0.6",
  }
```

**Comment by juan-manuel-alberro** [comment]
@rtivital thanks for the update but the SSR issue is still reproducible.
If you want, I can share my repo with you so you can take a look.

**Comment by rtivital** [comment]
@juan-manuel-alberro thanks, that will be perfect

**Comment by juan-manuel-alberro** [comment]
@rtivital you can find the code [here](https://github.com/juan-manuel-alberro/mantine-ssr-issue)
#### Steps
1. yarn
2. blitz dev (blitz needs to be installed globally)

On the home page (`"/"`) there are _partial styles applied_ (the button is working fine but the theme icon no), after you press the toggle theme icon it will be fixed. Then if you press the Login button it goes to the login page and the styles are OK.
If you refresh the `/login` page, there are no styles applied until you press the toggle theme icon.
Hope it helps.

**Comment by rtivital** [comment]
Thanks for sharing, there is an issue with styles generation on the client, usually when component with react-jss styles is mounted, styles are added via style tag – in this case it does not happen – styles are not regenerated on client after application was mounted. I need to dig deeper to find out why it works in all other Next apps, right now my main clue is react version and suspense which is used in your application. 

Meanwhile – it's safe to remove useEffect as in this cases ssr styles cannot impact your application in any case.

**Comment by juan-manuel-alberro** [comment]
Removing the `useEffect` works, partially, because when you switch themes you can see that the styles changes a little (something related with padding and margin)
Thanks.

**Comment by rtivital** [comment]
This is strange, I'm not able to reproduce layout jumping in your application (this was the case with ssr before 1.0.6) but now it should be fixed

**Comment by juan-manuel-alberro** [comment]
Yes, I'm not able to reproduce the layout jump with the 1.0.6.
I'll remove the useEffect and continue without that for now, thanks!

**Comment by rtivital** [comment]
All right, let's leave this issue opened for now, I want to get back some time later and see if it can be resolved

**Comment by Lalit2005** [comment]
Hi, I am having the same problem too..
I am using NextJs not BlitzJs.
When I run `npm run dev` for the first time, everything works fine. But when I refresh the page every styling disappears. Nothing too much is there in `index.js` 👇 
```jsx
// /pages/index.js

import {
  Image,
  Text,
  Overlay,
  Card,
  Container,
  Title,
  Button,
  ElementsGroup,
  useMantineTheme,
} from "@mantine/core";

export default function Home() {
  const theme = useMantineTheme();

  return (
    <div>
      <Container
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "20px 20px",
          width: "100vw",
        }}>
        <Title>Google</Title>
        <div style={{ display: "flex" }}>
          <Button
            size="lg"
            variant="outline"
            color="gray"
            style={{ marginRight: "20px" }}>
            Sign up
          </Button>
          <Button
            size="lg"
            variant="light"
            color="gray"
            style={{ border: "1px solid gray" }}>
            Login
          </Button>
        </div>
      </Container>
      <Container>
        <Title>Hello world</Title>
      </Container>
    </div>
  );
}

```

```jsx
// /pages/app.js

import { MantineProvider } from "@mantine/core";
import "../styles/globals.css";

function MyApp({ Component, pageProps }) {
  return (
    <MantineProvider>
      <Component {...pageProps} />
    </MantineProvider>
  );
}

export default MyApp;

```

### Whenever I refresh the page every styling goes away 👇 
![image](https://user-images.githubusercontent.com/69138026/117959653-dc921100-b339-11eb-97d1-ec649d9c95a7.png)

### And console throws a error 👇 
`Warning: [JSS] Rule is not linked. Missing sheet option "link: true".`

**Comment by juan-manuel-alberro** [comment]
@Lalit2005 that's a known issue from JSS, is mentioned in the Mantine doc https://mantine.dev/guides/ssr/#known-issues-with-nextjs

**Comment by rtivital** [comment]
@Lalit2005 just tried out clean installation with next.js with your code, cannot reproduce that, could you try attached folder and see if you can replicate this issue:
- download zip, extract it
- cd hello-mantine
- yarn 
- npm run dev

I'm suspecting that this may be related to broken next cache but I cannot reproduce the issue

[hello-mantine.zip](https://github.com/mantinedev/mantine/files/6465759/hello-mantine.zip)

**Comment by Lalit2005** [comment]
> @Lalit2005 just tried out clean installation with next.js with your code, cannot reproduce that, could you try attached folder and see if you can replicate this issue:
> 
> * download zip, extract it
> * cd hello-mantine
> * yarn
> * npm run dev
> 
> I'm suspecting that this may be related to broken next cache but I cannot reproduce the issue
> 
> [hello-mantine.zip](https://github.com/mantinedev/mantine/files/6465759/hello-mantine.zip)

Thanks!
Everything works now :)

**Comment by rtivital** [comment]
That's strange, if you ever face this issue again, please send me the zip with application (including next cache), I'll try to reproduce this on my side

**Comment by szmarci** [comment]
@rtivital I'm experiencing the same issue. With fresh next.js install:
`npx create-next-app --typescript`
Then I delete everything in `pages/index.tsx` and I insert just a button:
<img width="378" alt="Screenshot 2021-06-19 at 15 19 28" src="https://user-images.githubusercontent.com/1974290/122643779-06490f80-d112-11eb-8e27-83f19364291a.png">

At first it looks fine:
<img width="405" alt="Screenshot 2021-06-19 at 15 18 24" src="https://user-images.githubusercontent.com/1974290/122643791-182ab280-d112-11eb-87c0-a4f6266dd7b0.png">

Then I have to hit multiple page refresh to break it (if you hit it once or twice it is still okay), but once it is broken it is always broken, no matter if you refresh the page:
<img width="747" alt="Screenshot 2021-06-19 at 15 23 15" src="https://user-images.githubusercontent.com/1974290/122643924-c5052f80-d112-11eb-99ac-40cedb1f3f84.png">

**Comment by rtivital** [comment]
Hi @szmarci I guess you've missed the setup step for Next.js SSR, I've just created new test project, everything works fine – https://github.com/rtivital/next-ts-mantine

Please see documentation on usage with Next.js – https://mantine.dev/guides/ssr/#nextjs

**Comment by szmarci** [comment]
@rtivital Thanks, I really missed that. I thought it is was not relevant because there was no `_document.tsx` file after scaffolding the project. The styling was okay after refresh, however the error was still present in the console (I deleted the cache, npm reinstall, etc...). What did solve the console issue, was the deletion of the `next.config.js` file, which had the content:
```
module.exports = {
  reactStrictMode: true,
}
```
This file was not present in your repo, but it was autogenerated in mine. Weird.
Thanks again!

**Comment by rtivital** [comment]
Alright, I've investigated the issue with blitz and found out it uses experimental Suspense API, which does not support server side rendering, once it's out we will run some additional testing and fix an issue if this happens again, for now I'll close these issues

**Comment by zifeo** [comment]
@rtivital any idea why `reactStrictMode` cannot be enable with Mantine as @szmarci pointed out? This triggers the error even with the starter template (up-to-date or https://github.com/rtivital/next-ts-mantine).

**Comment by rtivital** [comment]
@zifeo I guess it's a react-jss strict mode issue, cannot say for sure what breaks there

**Comment by zifeo** [comment]
@rtivital likely found the root issue here: https://github.com/cssinjs/jss/issues/1522. At least it solves the styling one, but one error is left about `aria-controls`. How does mantine generate those hashes?
<img width="631" alt="image" src="https://user-images.githubusercontent.com/9053709/130230703-a38a2ca8-1172-47d1-88d1-1e34f0c8b511.png">

**Comment by rtivital** [comment]
@zifeo https://mantine.dev/core/menu/#server-side-rendering

**Comment by taktran** [comment]
Hi, I'm getting this issue with [Drawer](https://mantine.dev/core/drawer/) as well, but there doesn't seem to be the same fix with ids there? Does that need to be added?

**Comment by rtivital** [comment]
@taktran drawer is never rendered during ssr as it is wrapped in Portal, it much be another component that causes error

**Comment by taktran** [comment]
Actually @rtivital, I can replicate the bug with a fresh next.js install with just a `<Burger />` component - see https://github.com/taktran/next-mantine-bug

First render:

<img width="999" alt="burger-showing" src="https://user-images.githubusercontent.com/79451/131914497-467bebfb-9881-4c2d-a5f2-6330390bdf69.png">


After a couple of refreshes:

<img width="981" alt="burger-no-styles" src="https://user-images.githubusercontent.com/79451/131914515-83481f18-6ade-4802-b1e4-4f746c052a85.png">


The terminal console also shows:

```
Warning: [JSS] Rule is not linked. Missing sheet option "link: true".
```

---

Maybe something funky happens with ids for all mantine components during next.js dev mode?

**Comment by rtivital** [comment]
@taktran this happens because you did not setup ssr for next.js, see getting started section for more information

**Comment by taktran** [comment]
Oh cool, thanks @rtivital , I dug into it and this seems like a good reference https://github.com/vercel/next.js/tree/canary/examples/with-react-jss

I'll look into it when I get a chance

**Comment by rtivital** [comment]
@taktran why would you want to use it? We have all instructions on getting started page – https://mantine.dev/getting-started/ and ready to use template – https://github.com/mantinedev/mantine-next-template

**Comment by taktran** [comment]
Ah, that's even better! I was trying to find docs on the mantine site, but https://mantine.dev/guides/ssr seems to be a broken link. Missed that repo.

Thanks @rtivital!

**Comment by monlasan** [comment]
> Hi @szmarci I guess you've missed the setup step for Next.js SSR, I've just created new test project, everything works fine – https://github.com/rtivital/next-ts-mantine
> 
> Please see documentation on usage with Next.js – https://mantine.dev/guides/ssr/#nextjs

I faced the same issue after developing my project for few days...

It would be wise to put this simple nextjs-mantine starter template on Mantine UI Nextjs documentation... Not everyone need the overbloated next-js template present on the doc right now (what if i dont wanna use jest ?)... anyway everything work now on page refresh ... Thank you very much

AMAZING work by the way !!!... Mantine UI is really amazing... keep up the good work :D

**Comment by sladg** [comment]
I'm using lot of Grids and dynamic loading for certain components, on `next dev` styles would break for random parts of application.

Passing 
```
const cache = createCache({ key: 'css' })
```
as parameter to 
```
<MantineProvider
        withGlobalStyles
        withNormalizeCSS
        emotionCache={cache}
      >
        <Component {...pageProps} />
</MantineProvider>
```
fixed the issue for local development reloads.

Following above mentioned guides did not help.

**Comment by roHIT-MAN-45** [comment]
### Solution for **Mantine** SSR Styling Issue ( with next.js v13.4.2  )

1. Create emotion cache using **createEmotionCache** function.
`import { MantineProvider, createEmotionCache } from "@mantine/core";

// Creating emotion cache 📦
  const cache = createEmotionCache({ key: "css" });
`

2. Add **emotionCache** key to the **MantineProvider** 📌
`<MantineProvider
      theme={{
        colorScheme: theme,
        primaryColor: "orange",
        fontFamily: "Montserrat, sans-serif",

        // Colors
        colors: {},
      }}
      withGlobalStyles
      withNormalizeCSS
      emotionCache={cache}
    >
      <Notifications />

      {children}
    </MantineProvider>
`
3. Update the **next.config.js** 🔧
`/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

module.exports = nextConfig;
`

### Here is the **mantine.tsx** 💪
`
"use client";

// Libraries
import { MantineProvider, createEmotionCache } from "@mantine/core";
import { Notifications } from "@mantine/notifications";

// Redux
import { useSelector } from "react-redux";

interface ThemeState {
  theme: {
    theme: "light" | "dark";
  };
}

interface MantineStyleRegistryProps {
  children: React.ReactNode;
}

const MantineStyleRegistry: React.FC<MantineStyleRegistryProps> = ({
  children,
}) => {
  // Accessing theme 💅
  const theme = useSelector((state: ThemeState) => state.theme.theme);

  // Creating emotion cache 📦
  const cache = createEmotionCache({ key: "css" });
  return (
    <MantineProvider
      theme={{
        colorScheme: theme,
        primaryColor: "orange",
        fontFamily: "Montserrat, sans-serif",

        // Colors
        colors: {},
      }}
      withGlobalStyles
      withNormalizeCSS
      emotionCache={cache}
    >
      <Notifications />

      {children}
    </MantineProvider>
  );
};

export default MantineStyleRegistry;
`

### My **Package.json** ✨
`"dependencies": {
    "@emotion/react": "^11.11.0",
    "@mantine/core": "^6.0.11",
    "@mantine/dates": "^6.0.11",
    "@mantine/hooks": "^6.0.11",
    "@mantine/notifications": "^6.0.11",
    "@reduxjs/toolkit": "^1.9.5",
    "autoprefixer": "10.4.14",
    "dayjs": "^1.11.7",
    "next": "13.4.2",
    "postcss": "8.4.23",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "^4.8.0",
    "react-redux": "^8.0.5",
    "tailwindcss": "3.3.2",
    "typescript": "5.0.4"
  },
  "devDependencies": {
    "@types/node": "^20.1.7",
    "@types/react": "^18.2.6",
    "@types/react-dom": "^18.2.4",
    "cypress": "^12.12.0"
  }
`

🚨 Make sure to delete **.next folder (cache)** before running your project locally 🚀

🎉 Thankyou guys!

**Comment by roHIT-MAN-45** [comment]
### Solution for **Mantine** SSR Styling Issue (with Next.js v13.4.2)

#### Create emotion cache using the `createEmotionCache` function.

```javascript
import { MantineProvider, createEmotionCache } from "@mantine/core";

// Creating emotion cache 📦
const cache = createEmotionCache({ key: "css" });
```
#### Add the `emotionCache` key to the `MantineProvider`.

```javascript
<MantineProvider
  theme={{
    colorScheme: theme,
    primaryColor: "orange",
    fontFamily: "Montserrat, sans-serif",
    
    // Colors
    colors: {},
  }}
  withGlobalStyles
  withNormalizeCSS
  emotionCache={cache}
>
  <Notifications />

  {children}
</MantineProvider>
```

#### Update the `next.config.js`.

```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

module.exports = nextConfig;
```

## Here is the `mantine.tsx` file.

```javascript
// Libraries
import { MantineProvider, createEmotionCache } from "@mantine/core";
import { Notifications } from "@mantine/notifications";

// Redux
import { useSelector } from "react-redux";

interface ThemeState {
  theme: {
    theme: "light" | "dark";
  };
}

interface MantineStyleRegistryProps {
  children: React.ReactNode;
}

const MantineStyleRegistry: React.FC<MantineStyleRegistryProps> = ({
  children,
}) => {
  // Accessing theme 💅
  const theme = useSelector((state: ThemeState) => state.theme.theme);

  // Creating emotion cache 📦
  const cache = createEmotionCache({ key: "css" });

  return (
    <MantineProvider
      theme={{
        colorScheme: theme,
        primaryColor: "orange",
        fontFamily: "Montserrat, sans-serif",
        
        // Colors
        colors: {},
      }}
      withGlobalStyles
      withNormalizeCSS
      emotionCache={cache}
    >
      <Notifications />

      {children}
    </MantineProvider>
  );
};

export default MantineStyleRegistry;
```

## My `package.json` file.

```javascript
{
  "dependencies": {
    "@emotion/react": "^11.11.0",
    "@mantine/core": "^6.0.11",
    "@mantine/dates": "^6.0.11",
    "@mantine/hooks": "^6.0.11",
    "@mantine/notifications": "^6.0.11",
    "@reduxjs/toolkit": "^1.9.5",
    "autoprefixer": "10.4.14",
    "dayjs": "^1.11.7",
    "next": "13.4.2",
    "postcss": "8.4.23",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "^4.8.0",
    "react-redux": "^8.0.5",
    "tailwindcss": "3.3.2",
    "typescript": "5.0.4"
  },
  "devDependencies": {
    "@types/node": "^20.1.7",
    "@types/react": "^18.2.6",
    "@types/react-dom": "^18.2.4",
    "cypress": "^12.12.0"
  }
```

🚨 Make sure to delete **.next folder (cache)** before running your project locally 🚀

### Conclusion

In this solution, we addressed the **Mantine** SSR styling issue with Next.js v13.4.2. We created an emotion cache using the `createEmotionCache` function and added the `emotionCache` key to the `MantineProvider` component. Additionally, we updated the `next.config.js` file to enable React strict mode.

By following these steps, you can resolve the SSR styling issue and ensure a smooth development experience with **Mantine** and Next.js.

Remember to delete the `.next` folder (cache) before running your project locally to avoid any caching issues. Once everything is set up, you're ready to launch your project!

Thank you for using **Mantine** and happy coding!

**Comment by chinnuu05** [comment]
Has createEmotionCache been removed from Mantine v7? 

I am trying to prevent taiwlind preflight CSS from overwriting my Mantine Button styles, so I was going to use EmotionCache to do this, but I can't find createEmotionCache in @mantine/core anymore?
