### ISSUE TITLE
Poor performance of closed Popover component onScroll

### ISSUE THREAD

**Issue by yergom** [mantinedev/mantine#6771]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

All the components based on Popover (Combobox, Select, Tooltip) re-render too many times when their viewport position changes. As an example, try to profile the following code while scrolling on the ScrollArea:

```ts
<ScrollArea h={300}>
    {new Array(100).fill(0).map((_v, idx) => (
      <Select
        key={idx}
        data={["React", "Angular", "Vue", "Svelte"]}
      />
    ))}
</ScrollArea>
```

The performance problem is not present if, for example, we use `keepMounted = false` or the Popover is disabled. See attached codesandbox for a comparison

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-rtgqx7

### Possible fix

After looking at the implementation, I think that the main culprit is https://github.com/mantinedev/mantine/blob/00a94ceefc22c80ad08af73acb943f8f0c01d662/packages/%40mantine/core/src/components/Floating/use-floating-auto-update.ts#L19

As long as both refs are there, the effect will run the autoUpdate function. This explains why, when using `keepMounted:false`, the performance is fixed (because the `floating ref` is `null`). The fix is to only call `autoUpdate` if the floating is open

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.13.2](https://github.com/mantinedev/mantine/releases/tag/7.13.2)

**Comment by rcbevans** [comment]
I was getting user reported issues of browser hangs (and observing very poor page scrolling performance) which I just tracked down to this issue.  `comboboxProps={{ keepMounted: false }}` did fix, but just bumped mantine to 8.1.2 and this does seem to have resolved the horrible performance.

**Comment by kevinzaracho** [comment]
Hi! This issue is still happening on **8.1.3** unless you explicitly add

```js
comboboxProps={{ keepMounted: false }}
```

to every component built on top of Combobox, even when used inside a ScrollArea or a regular div with overflow.

Without keepMounted: false, scrolling causes massive unnecessary renders and performance drops, especially with large lists.

**Comment by rtivital** [comment]
I'll see if keepMounted can be turned off by default in Combobox
