### ISSUE TITLE
ScrollArea onButtonReached does not always call with decimal values

### ISSUE THREAD

**Issue by etwodev** [mantinedev/mantine#6792]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.12.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

in [ScrollArea](https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/components/ScrollArea/ScrollArea.tsx#L148-L151) there are instances where `scrollTop` is fractional, meaning `onBottomReached` will never be called - as this edge case is not handled, seen below:
```ts
          const { scrollTop, scrollHeight, clientHeight } = e.currentTarget;
          if (scrollTop - (scrollHeight - clientHeight) === 0) {
            onBottomReached?.();
          }
```
If `scrollTop` was a value such as 495.5, `scrollHeight` at 696 and `clientHeight` at 200, this would not call, despite being unable to scroll further.

### Possible fix

Replace

```ts
          const { scrollTop, scrollHeight, clientHeight } = e.currentTarget;
          if (scrollTop - (scrollHeight - clientHeight) === 0) {
            onBottomReached?.();
          }
```

with

```ts
          const { scrollTop, scrollHeight, clientHeight } = e.currentTarget;
          if (Math.abs(scrollHeight - clientHeight - scrollTop) < 1) {
            onBottomReached?.();
          }
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Kenzo-Wada** [comment]
I didn't reproduce on codesandbox environment, `Has Reached Bottom` become true :cry:

**Comment by etwodev** [comment]
> I see, I'll check it again on macos thanks! I was using Ubuntu...

Also realised my example was wrong, should work now in firefox now :)

**Comment by rtivital** [comment]
Fixed in [7.13.2](https://github.com/mantinedev/mantine/releases/tag/7.13.2)

**Comment by AlexeyEsin** [comment]
It still doesn't work with a certain number of entries in data. In my case, with 24 entries, onBottomReached does not work.

https://codesandbox.io/p/sandbox/mantine-react-template-forked-g7jynq

**Comment by chindathorn** [comment]
Also doesn't work when using ```Select``` v7.13.3 in Chrome but in Firefox works fine.
