### ISSUE TITLE
Unrecognized Prop Error in @mantine/charts

### ISSUE THREAD

**Issue by r-walsh** [mantinedev/mantine#7288]
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^7.15.1

### What package has an issue?

@mantine/charts

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

When using a `BarChart` and passing in `gridColor` and/or `textColor` props I receive the following error from React:

> Warning: React does not recognize the `gridColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `gridcolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

I suspect this is likely the same problem seen in [this issue](https://github.com/mantinedev/mantine/issues/6800) (and its [related PR](https://github.com/mantinedev/mantine/pull/6810)) in which props were being unintentionally spread across an element that can't accept them.

I was originally on version `7.7.2`, upgraded all mantine packages to `7.15.1` while looking for a fix and was still able to reproduce.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-yqwscq

### Possible fix

Assuming my intuition about the cause is correct, I expect a fix will follow the same pattern as the [PR](https://github.com/mantinedev/mantine/pull/6810) linked above on a similar issue.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.15.2](https://github.com/mantinedev/mantine/releases/tag/7.15.2)

**Comment by r-walsh** [comment]
@rtivital Thanks for the quick response! However it looks like `textColor` is still showing the issue
