### ISSUE TITLE
Select - Unexpected behavior when navigating with arrow keys

### ISSUE THREAD

**Issue by kamilmielnik** [mantinedev/mantine#7583]
### Dependencies check up

- [x] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.17.1

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

All

### Describe the bug

All scenarios reproducible with [this sandbox](https://codesandbox.io/p/devbox/recursing-swirles-forked-vp4zm6?workspaceId=ws_K5TupPTLNzT8kekXhssLLi).

**Scenario 1**
1. Click the Select component to focus it
2. Press arrow down 3x to select "Express" option
3. Type `d`
4. Press arrow down

Expected: first option is selected
Actual: last option is selected

**Scenario 2**
1. Click the Select component to focus it
2. Type `ex`
3. Press arrow down to select "Express" option
4. Press "backspace" key 2x
5. Press arrow up

Expected: 2nd option is selected
Actual: last option is selected

**Scenario 3**
1. Click the Select component to focus it
2. Type `e`
3. Press arrow down to select "Express" option
4. Press "backspace" key 2x
5. Press arrow down

Expected: 1st option is selected
Actual: 2nd option is selected

----

I tried adding `selectFirstOptionOnChange` prop but it also behaves unexpectedly.
The following scenarios are for the same sandbox just with `selectFirstOptionOnChange` prop added.

**Scenario 4**
1. Click the Select component to focus it
2. Press arrow down 3x to select "Express" option
3. Type `d`

Expected: first option is selected
Actual: no option is selected

4. Press arrow down

Actual: 2nd option is selected

**Scenario 5**
1. Click the Select component to focus it
2. Type `ex`

Expected: 1st option is selected
Actual: no option is selected

3. Press arrow down

Actual: 2nd option is selected

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/devbox/recursing-swirles-forked-vp4zm6?workspaceId=ws_K5TupPTLNzT8kekXhssLLi

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
Fixed in [7.17.3](https://github.com/mantinedev/mantine/releases/tag/7.17.3)

**Comment by ics460** [comment]
I am still able to replicate the unexpected behavior on 7.17.3
https://codesandbox.io/p/devbox/recursing-swirles-forked-37y6cm?workspaceId=ws_M919xktUgsm6fZaqKx5f9G

**Comment by kamilmielnik** [comment]
> I am still able to replicate the unexpected behavior on 7.17.3

I confirm scenarios 4 & 5 still don't work as expected (the ones with `selectFirstOptionOnChange` prop)

https://codesandbox.io/p/devbox/recursing-swirles-forked-lyj4mf

**Comment by rtivital** [comment]
Okay, I'll have a look at 4 and 5

**Comment by rtivital** [comment]
Fixed in [7.14.4](https://github.com/mantinedev/mantine/releases/tag/7.17.4)
