### ISSUE TITLE
Chip has a hardcoded SVG icon

### ISSUE THREAD

**Issue by OygnSR** [mantinedev/mantine#8382]
### Dependencies check up

- [x] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

^8.1.3

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

The Chip component has an icon that is predefined and hardcoded, it cannot be turned off, only replaced. The icon is also only visible when the chip is checked.

In our designs we use Leading and Trailing icons which are both optional. The default Chip behaviour works without an icon, then the user can add the icon. The icon is present regardless of the chips state, but it can also be shown conditionally based on the chips state. 

If we want to hide the default icon we have to do that via styles or classes, it works but it's a bit more hackish. 

<img width="1034" height="650" alt="Image" src="https://github.com/user-attachments/assets/9ceeb899-a105-461a-a4dc-952dd4de65a1" />

### Possible fix

To avoid a breaking change in the component, add an additional prop of something like `icon={false}` which would not show the icon at all times. 
To create the behaviour of showing the icon regardless of the state an additional prop of something like `alwaysShowIcon` could be set (false by default). This would create an additional functionality of the chip, to also show the icon when in unchecked state.

Additionally it would be great if we could have a trailingIcon prop, which would add the icon to the right part of the wrapper component. 

<img width="537" height="322" alt="Image" src="https://github.com/user-attachments/assets/8e142192-03cd-47d0-af4a-5d17e2110377" />

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment]
I've updated the component to support `<Chip icon={null}>With tooltip</Chip>`. It will be available in the next patch release.

**Comment by rtivital** [comment]
Fixed in [8.3.6](https://github.com/mantinedev/mantine/releases/tag/8.3.6)

**Comment by OygnSR** [comment]
Thank you for the fix. However the span icon wrapper for the icon still appears after setting the icon to `null` 

<img width="837" height="85" alt="Image" src="https://github.com/user-attachments/assets/31d598d0-3cd5-4883-a771-db39b5663795" />

I am guessing the trailing-icons are out of scope? 😄

**Comment by rtivital** [comment]
You can render trailing icons in chip label

I will remove iconWrapper when there is no icon in the next patch.

**Comment by zobweyt** [comment]
Thank you for the fix! Really needed this!

One issue remains: chip labels shift horizontally between checked/unchecked states. This causes visible layout jumps in chip groups:

https://github.com/user-attachments/assets/1859f04a-640c-46b4-8356-2303d6228a54

```tsx
<Stack gap="xs">
  <Title order={1} size="h2">
    Home
  </Title>
  <Chip.Group>
    <Group gap="xs">
      <Chip value="1" icon={null}>
        First
      </Chip>
      <Chip value="2" icon={null}>
        Second
      </Chip>
    </Group>
  </Chip.Group>
</Stack>
```

I think it's better to make the same padding if there is no icon

**Comment by rtivital** [comment]
There is actually no layout jump and it is intended behavior to avoid layout shifts for selected/deselected Chips. You can customize these styles with Styles API.

https://github.com/user-attachments/assets/e91679ab-192a-4783-9f06-c682be8de059
